name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment to run the tests'
        type: choice
        required: true
        options:
          - uat
          - sit

run-name: Running playwright tests on ${{ github.event.inputs.env }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run cucumber 
      run: TEST_ENV=${{ github.event.inputs.env }} WITH_IMAGE=true npm test --scheme="QLD"

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: cucumber-report.html
        retention-days: 30
