name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment to run the tests'
        type: choice
        required: true
        options:
          - uat

run-name: Running playwright tests on ${{ github.event.inputs.env }}

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Vault
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.svc.coexservices.com.au
        role: github-actions-role
        method: jwt
        path: github-actions
        exportToken: true

    - name: Export secrets from Vault
      id: export-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.svc.coexservices.com.au
        method: token
        token: hvs.CAESICT0I0xjCa2vk1K4l18Ln-DXICTvpGkjsQIvEqjIGEoBGh4KHGh2cy41clVySjNpQXlPZEt1cnY3dktaNTJRQW8
        run: vault kv get -format=json automation/fs-sales-volume-test-automation-env-sit | jq -r '.data.data | to_entries | map("\(.key)=\(.value|tostring)") | .[]' > .env
        
    - name: Show .env file content (for debug purposes)
      run: cat .env
